OpenSource-Communities/guestbook

.all-contributorsrc

Added Ayu Adiati and Edgar Figueroa as contributors. Ayu Adiati's contributions include question, blog, code, content, doc, example, mentoring, talk, and translation. Edgar Figueroa's contributions include code, data, doc, research, security, test, and translation.
_Generated using [OpenSauced](https://opensauced.ai/)._

FIX: Add contributors back to file

---

.all-contributorsrc
README.md

docs: add @franklyn883 as a contributor

---

.all-contributorsrc
README.md

docs: add @beckyrich as a contributor

---

README.md

Update the number

---

.all-contributorsrc
README.md

Added new contributor

---

.all-contributorsrc
README.md

This PR adds me as a contributor to the guest with the following contributions: code, doc, example, ideas and research. I want to do this to work on real world projects, improve my problem solving skills and become a better programmer.

docs: add @tedashikode as a contributor

---

.all-contributorsrc

- [X ] 🍕 Feature
- [ X] 🙅 no, because they aren't needed
- [ X] 🙅 no documentation needed

Add dxeon as contributor

---

.all-contributorsrc
README.md

docs: add @david-001 as a contributor

---

README.md

updated README.md step 7 #115

---

.all-contributorsrc
README.md

This PR is part of the Open Sauced Intro to Open Source course
Doesn't fix an issue
no need (I think)

docs: add @VirginieLemaire as a contributor

---

.all-contributorsrc
README.md

feat:  add my name 

---

.all-contributorsrc
README.md

I have taken the initiative to contribute to the OpenSauced project by manually adding my details to the guestbook. I am committed to learning more about open source and becoming an active member of this community.
In this pull request, I have made the necessary changes to the guestbook, providing my information and showing my commitment to being a part of this open source journey. By accepting this pull request, I hope to gain more experience and knowledge about open source development while actively participating in the OpenSauced project.
I appreciate the opportunity to contribute and look forward to your feedback and guidance on this journey. Thank you for considering my pull request.
feat: add {twister904} as a contributor

twister904 committed

---

i18n-guidelines.md

This PR revises a typo in the translation guide. I forgot to point this out in PR #157 
Relates to #144

fix: removing the "t" in the first heading

---

CONTRIBUTING.md
README.md

This PR adds the CONTRIBUTING.md file and links to it in the README.md
Closes #138

Added CONTRIBUTING.md, updated README.md

---

.all-contributorsrc
README.md

Added allwynvarghese to the Guestbook

---

.all-contributorsrc
README.md

This PR adds Ken-Musau ass a contributor

docs: add @Ken-Musau as a contributor

---

.github/PULL_REQUEST_TEMPLATE.md

This PR adds a PR template in the `.github` folder with related contents to this repo as follow:
- Adjusted the points in the "What type of PR is this?" and "Added to documentation?" sections.
- Added a "Contributors checklist" section.
Closes #169

feature: Add a PR template

---

.all-contributorsrc
README.md

- [✔ ] 🤝 Add a contributor
- [✔ ] ✅ Yes
- [ ✔] ⌨️ Manually
- [ ✔] ✅ Yes
- [ ✔] ✅ Yes
- [ ✔] 🙅 no documentation needed

 Add TejsinghDhaosriya as a contributor

---

.all-contributorsrc
README.md

Add victor-villca as a contributor.
:)

feat: Add victor-villca as a contributor

---

.all-contributorsrc
README.md

- [ x] 🤝 Add a contributor
- [x ] ✅ Yes
- [x ] ⌨️ Manually
- [ x] ✅ Yes
- [x ] ✅ Yes
- [x ] 📜 README.md

Add project-kieran as a contributor

---

.all-contributorsrc
README.md

This PR adds Mugabe000 as a contributor.

Add Mugabe000 as a contributor

---

.github/workflows/intro_course_contributor.yml

Update intro_course_contributor.yml to remove repeat messages

---

.all-contributorsrc
README.md

docs: add @hyosung11 as a contributor

---

.all-contributorsrc
README.md

docs: add @snehalk19 as a contributor

---

.all-contributorsrc
README.md

feat: Add ChiaBeaCode as a contributor

---

.github/PULL_REQUEST_TEMPLATE.md

Lately, there has been a handful of Pull Requests that missed the step of generating profile and badge on the README. So, @adiati98, @BekahHW, and I agreed that the PR template needs a section called "Screenshot" with instructions after the "Added to documentation?" section.  By providing this information, maintainers would have an easier time reviewing PRs and ensuring that contributors followed the steps to adding their profile.
Closes #198 
- Have you run `npm run …

docs: add screenshot requirement to PR template

---

.github/PULL_REQUEST_TEMPLATE.md

fix: reformat template

---

CONTRIBUTING.md

Closes https://github.com/open-sauced/guestbook/issues/209
This PR makes adjustments to some wording in the Contributing Guide: 
This Contributing Guide will walk you through how to contribute to this project for bug fixes and features. If you want to contribute to the guestbook, please refer to [chapter five](https://intro.opensauced.pizza/#/05-how-to-contribute-to-open-source) of the Intro to Open Source course.
Navigate to and open the project in your code editor.

Docs: adjust wording in the contributing guide

---

.github/workflows/ISSUE_TEMPLATE/feature_request.yml

This PR adds a feature issue template for adding contributors. This will encourage people who have taken the Intro to Open Source course to practice raising and writing an effective issue. 
Closes #206 
Closes #203

docs: add feature issue template for adding contributors

---

.github/PULL_REQUEST_TEMPLATE.md

Add Required to Screenshot

---

.github/PULL_REQUEST_TEMPLATE.md

Feat(PR Template): Update PULL_REQUEST_TEMPLATE.md to emphasize compulsory screenshot

---

.all-contributorsrc
README.md

This PR adds @chrisVCH as a contributor.
😃

feat: Add @chrisVCH as a contributor

---

.github/workflows/intro_course_contributor.yml

We are still seeing multiple messages to PRs bc of our GH action. I think removing syncronize should fix it.

fix: remove syncronize from action

---

.github/CODEOWNERS

This PR fixes the syntax format in CODEOWNERS file so that the code owners can be automatically added as reviewers.
Fixes #236

fix: syntax format in CODEOWNERS

---

.all-contributorsrc
README.md

Adds Haimantika as a contributor in the guestbook.

feat: Add Haimantika as a contributor

---

.all-contributorsrc
README.md

This PR adds Neerajrawat123 as a contributor.
🤝 Add a contributor
✅ Yes

docs: add @Neerajrawat123 as a contributor

---

.github/workflows/intro_course_contributor.yml

This PR modifies the greeting message. It tags the contributor's name, making them feel welcomed!  
Closes #239

feat: made the greeting more personalized

---

.all-contributorsrc
README.md

Incorrect links and term's consistency on the README are fixed for clarity
Closes #245 
- [x ] 📝 Documentation Update
- [x ] ✅ Yes
- [x ] 🤖 With CLI
- [x ] ✅ Yes
- [x ] 📜 README.md
📖📖 It felt so good and I learned a lot. I feel very good thank you

fix: incorrect links and term's consistency on the README

---

.all-contributorsrc
README.md

- [ x] ✅ Yes
- [x ] 📜 README.md
📖 It felt so good and I learned a lot

feat: Add @safaanilatasoy as a contributor

---

.all-contributorsrc
README.md

docs: add @lukepadiachy as a contributor

---

.all-contributorsrc
README.md

This PR adds LuisCFunes as a contributor.
- [] 📝 Documentation Update
Closes #264
- [ x ] ✅ Yes
- [ x ] ✅ Yes
- [ x ] 📜 README.md

feat: Add @LuisCFunes as a contributor

---

.all-contributorsrc
README.md

In this PR I add myself as a contributor in the readMe markdown.
Closes #267

feat: Add @SimonGideon as a contributor

---

.all-contributorsrc
README.md

This PR adds JohnMwendwa as a contributor.
Closes #266

feat: add @JohnMwendwa as a contributor

---

.all-contributorsrc
README.md

This PR adds paulrwade as a contributor, as we are encouraged to do in the Intro to Open Source course.
- [ x] 🤝 Add a contributor
- [ x ] 📝 Documentation Update
closes #298 
- [ x] ✅ Yes
- [ x] ✅ Yes
- [x ] 📜 README.md

docs: add @paulrwade as a contributor

---

.all-contributorsrc
README.md

it is not  difficult.but i clone by ssh ,not by http 。i can not push by http!
but I still feel exicted! 
Thanks so much!
forgive my poor English.
closes #302

docs: add @jiuyueshenhua as a contributor

---

README.md

This PR changes the open-sauced/guestbook's README file's logo to the new, dark version -- fixes the alt tag, and removes the width attribute.
- [ X] 📝 Documentation Update
Closes #273 
- [X ] ✅ Yes
- [ X] ✅ Yes <-- In an earlier PR
- [X ] 📜 README.md

updated logo in guest book

---

.all-contributorsrc
README.md

This PR adds syke9p3 as a contributor.
Closes #305

feat: add @syke9p3 as a contributor

---

.github/workflows/compliance.yml

This PR adds the compliance workflow to check if a PR is following our standard and convention. I applied the same workflow as in the [docs repo](https://github.com/open-sauced/docs/blob/main/.github/workflows/compliance.yml).
Closes #307 
The changes here are not related to adding contributors to the guestbook.
N/A

feat: add compliance workflow

---

.github/workflows/intro_course_contributor.yml

This PR updates the message of the PR_COMMENT in `intro_course_contributor.yml` to reflect the latest updates of the course.
GitHub action update.
Fixes #313 
This PR is not to add contributors to the guestbook.
N/A

fix: update message of the PR_COMMENT in `intro_course_contributor.yml`

---

.github/workflows/intro_course_contributor.yml

This PR fixes the intro course contributor action that keeps failing by removing the double quotes that wrap a chapter's title.
Fix bug
Fixes #323 
This PR doesn't add a contributor.

fix: intro course contributor action

---

.all-contributorsrc
README.md

This PR adds @Alok-Jadhao as a contributor.
Closes #354

feat: Add @Alok-Jadhao as a contributor

---

CONTRIBUTING.md

This PR changes Discord and its link to Community.
Fixes #358

fix: change Discord to Community

---

.all-contributorsrc
README.md

This PR adds @skottchen as a contributor.
Closes #367

feat: Add @skottchen as a contributor

---

.all-contributorsrc
README.md

This PR adds @favourachara07 as a contributor.
Closes: #448

feat: Add @favourachara07 as a contributor

---

.all-contributorsrc
README.md

This PR adds @badxcode as a contributor.
Closes #426

feat: Add @badxcode as a contributor

---

.all-contributorsrc
README.md

This PR fixes #454 by adding max-deathray as a contributor.
Fixes https://github.com/open-sauced/guestbook/issues/454

feat: Add @max-deathray as a contributor

---

.all-contributorsrc
README.md

This PR adds @WybsonSantana as a contributor.
Closes #472

feat: Add <@WybsonSantana> as a contributor and fill in all areas in the pull request template. 

---

.all-contributorsrc
README.md

Added @allanoguis as contributor.
Closes #503

docs: add @allanoguis as a contributor

---

.all-contributorsrc
README.md

- [ x ] 🤝 Add a contributor
- [ x ] 📝 Documentation Update
Closes #512 
- [ x ] ✅ Yes
- [ x ] ✅ Yes
- [ x ] 📜 README.md
For Work In Progress Pull Requests, please use the Draft PR feature,
see https://github.blog/2019-02-14-introducing-draft-pull-requests/ for further details.
For a timely review/response, please avoid force-pushing additional
commits if your PR already received reviews or comments.
Before submitting a Pull Request, please ensure you've done the following:
- 📖 Read the Open Sauced Contributing Guide: https://github.com/open-sauced/.github/blob/main/CONTRIBUTING.md.
- 📖 Read the Open Sauced Code of Conduct: https://github.com/open-sauced/.github/blob/main/CODE_OF_CONDUCT.md.
- 👷‍♀️ Create small PRs. In most cases, this will be possible.
- 📝 Use descriptive commit messages. …

docs: add @02zeda as a contributor

---

.all-contributorsrc
README.md

This PR adds @koja-amir as a contributor.
- [✅] 🤝 Add a contributor
Closes #523
- [✅] ✅ Yes
- [✅] ✅ Yes
- [✅] 🙅 no documentation needed

docs: add @koja-amir as a contributor

---

.all-contributorsrc
README.md

This PR adds @mrutunjay-kinagi as a contributor.
Closes #531

feat: add @mrutunjay-kinagi as a contributor

---

.all-contributorsrc
README.md

This PR adds @Firdous2307 as a contributor.
Closes #533

docs: add @Firdous2307 as a contributor

---

.github/PULL_REQUEST_TEMPLATE.md

This PR addresses an issue where some contributors wrote their PR description and/or related issue inside comment tags, causing the information to be hidden in preview mode. This update clarifies that PR details must be written outside the comments in the PR template.
Additionally, it corrects the example issue number, as some contributors have used the example issue number instead of their actual issue number.
Closes #521.
(Screenshot here)

docs: Added information to write PR details

---

.all-contributorsrc
README.md

This PR adds @gaffarabdul as a contributor.
Closes #544 
:smile:

feat: Add @gaffarabdul as a contributor

---

.all-contributorsrc
README.md

This PR adds @sridhar-geek as a contributor.
Closes #541

docs: add @sridhar-geek as a contributor

---

.all-contributorsrc
README.md

This PR adds @satyam0827 as a contributor.
Closes #551

docs: add @satyam0827 as a contributor

---

.all-contributorsrc
README.md

This PR adds @pyogi27 as a contributor
Closes #606

docs: add @pyogi27 as a contributor

---

.all-contributorsrc
README.md

This PR adds @BrodyWills as a contributor
Closes #625

feat: add @BrodyWills as a contributor

---

.all-contributorsrc
README.md

This PR adds @irisxvii as a contributor.
Closes #628

docs: add @irisxvii as a contributor

---

.all-contributorsrc
README.md

This PR adds [@Aftar-Ahmad-Sami](https://github.com/Aftar-Ahmad-Sami) as a contributors
Closes #637

docs: add @Aftar-Ahmad-Sami as a contributor

---

.all-contributorsrc
README.md

This PR adds @quartel as a contributor.
Closes #643

docs: add @quartel as a contributor

---

.all-contributorsrc
README.md

This PR adds @Rijan-Joshi as a contributor
- [x ] 🤝 Add a contributor
Closes #645 
- [x ] ✅ Yes
- [ x] ✅ Yes
- [ x] 📜 README.md

feat: Add @Rijan-Joshi as a contributor

---

.all-contributorsrc
README.md

This PR add @ArchILLtect as a contributor
Closes #665

feat: Add ArchILLtect as a contributor

---

.all-contributorsrc
README.md

This PR adds @muou000 as a contributor.
Closes #667

docs: add @muou000 as a contributor

---

.all-contributorsrc
README.md

This PR adds @shampost as a contributor
Closes #673

feat: add @shampost as a contributor

---

.all-contributorsrc
README.md

This PR adds @hritikyadav07 as a contributor.
Closes #676

feat: add @hritikyadav07 as a contributor

---

.all-contributorsrc
README.md

This PR adds @AngelMancilla as a contributor.
Closes #681

feat: Add <@AngelMancilla as a contributor

---

.all-contributorsrc
README.md

This PR adds @Spcxx as a contributor.
Closes #697 
N/A

feat: Add @Spcxx as a contributor

---

.all-contributorsrc
README.md

This PR adds @porteristhechampion as a contributor
Closes #737

feat: Add porteristhechampion as a contributor

---

.all-contributorsrc
README.md

This PR adds topSimpa as a contributor
Closes  #757
]

docs: add @topSimpa as a contributor

---

.all-contributorsrc
README.md

This PR adds @algacyr-melo as a contributor.
Closes #787

feat: Add @algacyr-melo as a contributor

---

.all-contributorsrc
README.md

This PR adds @Hardik-S-003 as a contributor.
Closes #794

feat: Add @Hardik-S-003 as a contributor

---

.all-contributorsrc
README.md

This PR adds @blobmister as a contributor.
Closes #821.

docs: add @blobmister as a contributor

---

.all-contributorsrc
README.md

This PR adds @Nabinbista12 as a contributor.
Closes #813

feat: add @nabinbista12 as a contributor
